apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: nginx.vectoria.online

spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
