apiVersion: v1
kind: Service
metadata:
  name: external-grafana
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
#  selector:
#    app: nginx-dep
  ports:
  - port: 3000
    protocol: TCP
    name: http
    targetPort: 3000

#  selector:
#    app: nginx-dep.argocd
