apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: nginxtest
  name: nginxtest
  
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginxtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginxtest
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginxtest
